### ISSUE TITLE
Not Sending Votes

### ISSUE THREAD

**Issue by noahjgreer** [clragon/e1547#101]
When trying to upvote or downvote a post, it will appear to work, but when you reload the app and open the same post, it doesn't seem to register your vote.

**Comment by noahjgreer** [comment]
https://github.com/clragon/e1547/assets/68797338/32c8f698-2c51-4122-8205-cedbceeeb993

**Comment by clragon** [comment]
Unfortuantely, votes are not sent over the API by e6, so the app cannot know whether you have upvoted a post or not.
When you upvote a post, the app will display the vote for the duration of the search page being open. After that, it no longer has this information. However, if you visit the site in your browser, the vote will be displayed correctly, because they are using html generation directly from the database, which is not available to e1547.

To accommodate for this, votes in the app will always overwrite the previous vote if the app doesnt know if you have voted on a post, so upvoting a post twice will not undo your vote. This is the only thing we can do without actual support from e6. 
I hope this clears things up for you.
