### ISSUE TITLE
Cache the bookmarked pools inside the application

### ISSUE THREAD

**Issue by Terkyz** [clragon/e1547#125]
**Is your feature request related to a problem? Please describe.**
Not at all, and I know you're already working on #123, but that's not exactly the same thing, so I didn't say it there. 

**Describe the solution you'd like**
When you bookmark a pool, the images in the pool are cached in the app and can be accessed at any time.

**Describe alternatives you've considered**
I can download the images directly and sort them into a directory, but I wish this was implemented directly in the app.

**Additional context**
That's all, thanks!

**Comment by clragon** [comment]
Hi, thanks for your issue.

If you are looking for a feature that allows you to access pools while offline, 
this will not work with the current state of the application.
Even if images were cached, the app would need to request the Posts of said Pools to display them.
The app doesnt have any interface to directly view images without Posts.

Your suggestion does fit into the subset of a larger feature, which would be the ability to save parts of the site into a local database which can then be browsed just like the site itself.
Such a feature is within the reach of our possibilities because of new, ongoing developments taking place right now.
However, the actual development time of this feature is unpredictable at the moment and most possibly very large, speaking the order of years.

Does this align with your request?

**Comment by Terkyz** [comment]
Yes, actually that looks very promising and even better than what I asked for.
