### ISSUE TITLE
Option to disable swipe-from-side gestures for android gesture navigation compatibility

### ISSUE THREAD

**Issue by hjake123** [clragon/e1547#132]
**Is your feature request related to a problem? Please describe.**
On android, using the gesture-based navigation scheme, swiping from the left or right of the screen is the gesture for the "back" input. This conflicts with the sidebar menu mapped to swipe from right and can behave strangely.

**Describe the solution you'd like**
The sidebar gesture could either turn itself off in gesture navigation mode, or there could be an option in the Interactions settings menu to disable the swipe gestures for this app.

**Comment by clragon** [comment]
This is unlikely to be a feature because removing the swipe gesture will make it entirely impossible to open the drawer at all, in certain screen configurations. 
Personally I think swipe-to-go-back is just not a very good paradigm in OS design because swiping should be reserved for the UI of actual applications, just like in this case here.

**Comment by Ketoro** [comment]
you could make swiping functionality limited to the middle portion and exclude the space near the sides like how some apps do it.

**Comment by hjake123** [comment]
Alright, understandable
