### ISSUE TITLE
e1547 assumes no search results if first page is empty

### ISSUE THREAD

**Issue by themostlogicalsolution** [clragon/e1547#135]
**Describe the bug**

The first page of a search may be blank if every single post on the page is blacklisted. If this happens, e1547 will assume there are no posts that fit the search.

**To Reproduce**

1. Use the client https://e621.net
2. Add "rating:e" to the blacklist
3. Search "order:score"

(These steps may become outdated if a non-explicit post makes it on the first page of order:score)

**Expected behavior**

Ideally, posts load as usual. If this isn't possible (I wouldn't know, I'm not familiar with the e621 API), the user might be prompted with a button to attempt to load the next page

**Platform**

 - Device: Samsung Galaxy S22
 - OS: Android 
 - Version 14

**Additional context**

This issue is not very important, and can be solved by the user by excluding the offending blacklist items directly in the search (eg: searching "order:score -rating:e" instead of "order:score" when rating:e is blacklisted)

This issue is also very much an e621 issue. I only bring it up because the issue is worse here (blank pages vs. "no results" page), and this problem could realistically be solved here too.

**Comment by clragon** [comment]
Hi,

Thanks for your issue. We've thought about this problem too, when we implemented the code for it.
The reason that we didn't implement this behviour is two-fold:
1. makes the code complicated and messy because we have to add extra effects
2. might get us into a situation where we load many (or infinite) amount of pages

the first one is excusable, the second one not so much.
because of that, its unlikely we'll ever fix this, unfortunately.

best regards!
