### ISSUE TITLE
The app consume TOO MUCH mobile data

### ISSUE THREAD

**Issue by Terkyz** [clragon/e1547#139]
**Describe the bug**
Sometimes I just want to search scroll through e621 using e1547, but 5 minutes scrolling consume easily 500MBs of data, and I don't have a unlimited plan so that's a lot for just 5 minutes.

**To Reproduce**

1. Open the app, using mobile data.
2. Just scroll a while.
3. Check how many data had used the app.

**Expected behavior**
If I understand correctly, e1547 load the version of the image instead of the default and that consume a dramatic amount of data... I'm not sure if there's something that can be done to fix this, but I hope so.

**Platform**

 - Device: Samsung A31
 - OS: Android
 - Version 12
 - Using latest version of the app.

**Comment by clragon** [comment]
Hi @Terkyz 

We have done an investigation and concluded that unfortunately, the app is working just as intended.
The app uses "sample" pictures (~800px) instead of "preview" pictures (~150px).  Those sample pictures are around 200kb when large. For 500 mb you can roughly scroll through 2500 pictures. One page of JSON data from e6 is ~250kb. 

The "preview" pictures are too small for the grid view of most phones and will look blurry. 
Therefore, we cannot "fix" this issue. We are very sorry!
