### ISSUE TITLE
Video deformation on playing

### ISSUE THREAD

**Issue by mindsolve** [clragon/e1547#29]
Dear dev, I have been using your app for quite a while now and am very happy - with one exception: videos (not gifs) are almost unusable.

If I try to play a video in the app, the actual video shrinks to some random small size (with wrong aspect ratio) and the rest of the video area turns green. See the following (SFW) screenshot of this post: https://e926.net/posts/2899523

![Screenshot_20210901_225855_net e1547](https://user-images.githubusercontent.com/24863329/131745131-0b0055f6-7f50-4c41-98a7-fbfafc9e896d.jpg)

The video plays in itself normally (including audio) in that strange formfactor.

I am using the newest app version (`1.8.1`) on Android 10. What additional information do you need to properly diagnose this?

Best regards,
MindSolve

**Comment by clragon** [comment]
Hi there,
thanks for reporting this.

It looks like this issue is a device (mate 10) and or os version (android 10) specific.

I have taken a closer look and this is an upstream issue inside a library the app is using.
I could try to replace video_player with flutter_vlc_player and this might solve it.

However, this replacement might take quite some time and effort.

**Comment by mindsolve** [comment]
Oh, interesting - and unfortunate. Those bugs are always the worst, hiding somewhere in an important dependency :smile:.

Do you have any other problems with the video_player library or would my issue be the only reason to change the library?
Maybe there are other workarounds for this problem? Like disabling hardware decoding (as an optional setting)?

**Comment by clragon** [comment]
well there is the prospect of vlc offering caching of videos, which video_player does not whatsoever...
And that might be worth pursuing.

there's also the curious issue of having to manually control all the videos that are loaded into video_player in a global list, because it will not automatically dispose of them. I am unsure how that would change with vlc.

I also have the hope that I would not need to change too much. I have invested alot in making the app itself abstract enough so replacing the video player might not be too big of a task.

I dont think the video_player library allows disabling hardware decoding, as exo player, the library used for the android part of video_player, is hidden away behind it.

**Comment by clragon** [comment]
I have taken a closer look and decided that we will most likely not switch to vlc_player.
This issue is therefore purely upstream and we cant do anything about it from our side.

**Comment by mindsolve** [comment]
Okay, thank you anyway for having a look and considering it! 👍

**Comment by mindsolve** [comment]
@clragon I don't know when it happened (but somewhat recently), but videos now fully work on the same device! No more green bars, no more streched or resized to invisible videos! Thank you!!!
