### ISSUE TITLE
Resolution options for videos

### ISSUE THREAD

**Issue by Drawmahs** [clragon/e1547#37]
On the website, when viewing large images, they are shown in a lower resolution until the user himself wants to view it in full resolution. Your app has it too and it works great. But I think that such a function should also be added to videos and animations. It is also present on the site (screenshots attached) and some videos are uploaded in 2k, or even in higher resolution, which kills traffic and device RAM, which causes the application to crash. It will be great to be able to select samples in 480 and 720 right in the app! 
![Screenshot_1](https://user-images.githubusercontent.com/42215455/141116281-61bde77f-fec5-4d4a-b4c9-95c0cfb0b4ad.png)
![Screenshot_2](https://user-images.githubusercontent.com/42215455/141116295-053438ea-0d15-4f7d-87ff-1bc88cc256a9.png)

**Comment by clragon** [comment]
Hi,

Thank you for your suggestion.
This would be indeed an interesting feature, however currently I am unsure how it would be integrated into the UI.

I will definitely consider adding this in the future.

**Comment by Dividedby0KSJ** [comment]
### Came to the GitHub to ask this exact thing.\

My phone is an low budget A13 and it struggles to load almost all videos. (some work perfect, I assume a low bitrate or resolution on the video)
however most videos have a high bitrate/resolution that the phone cant handle in the app.

My temporary solution has been to use the "Browse" button to open the videos webpage and watch it there (with the sample 720p) 

> Another solution is to download the video and watch it from VLC app. I don't know why VLC can process the video while e1547 cannot [Side note, some videos don't work in VLC regardless of it being downloaded]

**Comment by SirDubbingtonIV** [comment]
For lower end devices this would help a lot. Most media players for me refuse to play anything bigger than 1920x1080 resolution videos, and so I either have to save every high resolution video I want to watch and watch it in a media player that will play high resolution videos (this is a hassle because of the lack of storage space on mobile devices) or I simply can't. It makes browsing image boards frustrating when I'm not at my computer.

**Comment by clragon** [comment]
I see this issue has a lot of interest. I will bump it in the list of priorities.
Thank you for your feedback, everyone.

**Comment by clragon** [comment]
feature spec:

1. introduce an option to select the resolution of a video being played, picking from available resolutions.
2. introduce a "preferred video resolution" setting picking an Enum [480p, 720p, 1080p, 4k, Native]
which is used to find the default resolution a video should be played at. 
if a video has a resolution higher than the preferred resolution but still within 10%, it will be chosen regardless.
resolution is calculated x*y without accounting for orientation.
Native resolution means the highest available.

**Comment by clragon** [comment]
this feature now exists.
I dropped the ability to decide video resolution on the fly because that is somewhat complex to manage in the current setup, unfortunately.
however, there is now a setting to control the default video resolution and it will correctly pick the video closest to that resolution.
an option to pick resolution for each video might still come later. 
this will be released with the next version of the app.
