### ISSUE TITLE
Solving the problem of broken apk with 31 SDK

### ISSUE THREAD

**Issue by Drawmahs** [clragon/e1547#44]
Hi, slragon! 

I think I found the reason why the apk releases are broken. the problem seems to be present on Android 11 and above. The android website states that starting from API Level 30, not only the APK v1 Signature Scheme is required, but it should be also signed using the APK v2 signature scheme or higher. I believe you're more experienced with these requirements. I'm sending a link and a screenshot.
Hope this'll help you in the development, can't wait for a store release version!

https://developer.android.com/about/versions/11/behavior-changes-11#minimum-signature-scheme

![Screenshot_1](https://user-images.githubusercontent.com/42215455/143568735-b6bf9f90-e13c-4793-b6bc-851278290f92.png)

**Comment by clragon** [comment]
Hi,

Thanks for telling me. I am unsure if this is the problem, because certain users have reported being unable to install the app even from the playstore.

Since the playstore signs the app bundles themselves instead of me compiling the APK and since the playstore is basically google, I would assume they would be signing the resulting APK with both the old and new signature scheme.

But we cant be too sure, so I will go check. If i find something, I will let you know. thanks again.
