### ISSUE TITLE
iOS app ID

### ISSUE THREAD

**Issue by clragon** [clragon/e1547#6]
It's currently not possible to compile the app for iOS as `com.e1547`, as this name is already taken. 
I assume that is because @perlatus has registered it. 

I haven't found a way to contact perlatus, therefore I am writing this issue.

**Comment by perlatus** [comment]
Heyo. First off just wanted to say I really appreciate what you've done to improve the app! The UI is so much better than what I was able to hack together.

For the app IDs, I was using `io.vczf.e1547` and later changed it to `us.perlat.e1547`. That's because I rent the `perlat.us` domain and used to rent the `vczf.io` domain.

I don't think there is a limitation on who can use what ID for compiling. You need a unique ID for publishing to app stores and for keeping settings/state when upgrading, and a domain name is convenient for that.

Perhaps try changing the ID to `app.clragon.e1547` and see if that works? You don't need to own the domain to use it as a reverse domain name notation id.

**Comment by clragon** [comment]
Hi,

Thanks for the reply. Thats awesome, I was really hoping you'd like the changes. I really loved the original app, and I felt like working towards your vision, I'm still keeping an eye on those old issues of the now archived repo now and then.

That with the ID is weird, but @CamperGuy didn't seem to manage to compile it with `com.e1547`.
Maybe this will help him though.

Of course it doesnt have to be the website name, but I secretly have the unlikely dream of compiling this to web, desktop and mobile, then renting the site and making a complete cross-platform interface. 

More of a distant dream tho, alot of things to go to there, and currently I just want forum support.

**Comment by KritantaDev** [comment]
com.e1547 is fine for iOS builds; users installing it should typically change it themselves and add a unique portion to the id if needed.
