### ISSUE TITLE
Use combined API calls for single tag follows

### ISSUE THREAD

**Issue by TDOWuser** [clragon/e1547#75]
Currently the loading of the follows tab is extremely slow. Seems like you're sending a seperate request for every tag to e621. Can't it be done that all singular normal tags are sent in one big request using the ~ prefix? (https://e621.net/help/cheatsheet#searching_basics)
Would already make it a lot faster in my case.

**Comment by clragon** [comment]
we are intentionally making a request _per search_ (not per tag) so that any valid search can be followed.

**Comment by TDOWuser** [comment]
thats why I ask to filter out the abnormal tags and only do it for singular normal ones. Would atleast speed up the process for every normal tag.

**Comment by clragon** [comment]
the problem with doing that is that it makes the logic very complicated. 
there would need to be a mechanic to separate follows to run batched updates and then we would have to find some way of splitting the request into sensible data.

**Comment by clragon** [comment]
after some thinking, we have devised a strategy for how this could work.
I think I might attempt to implement this in that case.
the speed up could be well worth it,
even if this increases the client complexity which I am not a fan of.

thanks again for bringing this topic to my attention once more.

**Comment by clragon** [comment]
for the record:

- collect all single tag follows
- chunk them into packages of max 40, but evenly distributed
(example: 60 should be [30,30] not [40,20])
- make requests with limit 200, resulting in a desired 5 posts of each tag
(because of how ~ works, this does _not_ guarantee _any_ posts for a tag, however)
- split the result by tag (simply iterate and check for the tag) and notify the follows
- if a tag has gotten _no_ posts in the result or if all posts in the result are _new_, make a separate request for that tag
- finally, process all the multi-tag follows with a single request each

**Comment by TDOWuser** [comment]
> for the record:
> 
> * collect all single tag follows
> * chunk them into packages of max 40, but evenly distributed
>   (example: 60 should be [30,30] not [40,20])
> * make requests with limit 200, resulting in a desired 5 posts of each tag
>   (because of how ~ works, this does _not_ guarantee _any_ posts for a tag, however)
> * split the result by tag (simply iterate and check for the tag) and notify the follows
> * if a tag has gotten _no_ posts in the result or if all posts in the result are _new_, make a separate request for that tag
> * finally, process all the multi-tag follows with a single request each

This is basically how I did it in my makeshift react app that I made when I was bored. (It can't be found on my github).
