### ISSUE TITLE
Three small feature requests and one small issue

### ISSUE THREAD

**Issue by DavidRLTG** [clragon/e1547#79]
1. When images are loaded, only a lower-resolution preview is shown to make loading times faster.
2. Could we please have a settings to have the tags reset when app is closed? Thank you.
3. Could rounded corners on posts be disabled, please? pretty please.

And please, could the video player be improved in any way? it's way too simple, and it loads slowly in my opinion.

**Comment by clragon** [comment]
1. we cannot make images any smaller than they already are without making them visibly pixelated
2. if you wish to not change the home tags, you can instead open the drawer and click "Search"
3. I do not think that I will add an option to disable rounded corners on tiles

I am not sure what you mean by "too simple".
Improvements to the videoplayer would be upstream issues. 
Unfortunately there is no caching for the video player as of right now.

**Comment by DavidRLTG** [comment]
Oh, understood. Still would've liked to make images load faster by a lower res or disable rounded corners, but okay.

**Comment by clragon** [comment]
e6 images only come in three different resolutions, preview, sample and file.
e15 deliberately uses sample instead of preview (the site uses preview),
because previews are around 100x100, while samples are around 1000x1000,
and using the previews in the grid looks terribly pixelated (at tile the default tile sizes of 200).
I do not think that making that available would be a nice user experience.
loading previews in the grid would also increase introduce a new loading time when actually opening the post.
